Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
display(Markdown(FileCodeBox(
    file=exdir + "/empty.s", 
    lang="gas", 
    title="<b>CODE: Our very own 'empty' binary</b>",
    h="100%",
    w="70em"
)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[24], line 1[0m
[0;32m----> 1[0m display(Markdown([43mFileCodeBox[49m[43m([49m
[1;32m      2[0m [43m    [49m[43mfile[49m[38;5;241;43m=[39;49m[43mexdir[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43m/empty.s[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      3[0m [43m    [49m[43mlang[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mgas[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      4[0m [43m    [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m<b>CODE: Our very own [39;49m[38;5;124;43m'[39;49m[38;5;124;43mempty[39;49m[38;5;124;43m'[39;49m[38;5;124;43m binary</b>[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      5[0m [43m    [49m[43mh[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m100[39;49m[38;5;124;43m%[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      6[0m [43m    [49m[43mw[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m70em[39;49m[38;5;124;43m"[39;49m
[1;32m      7[0m [43m)[49m))

File [0;32m/opt/app-root/src/under-the-covers-jm/content/python/common.py:67[0m, in [0;36mFileCodeBox[0;34m(file, lang, number, **kwargs)[0m
[1;32m     65[0m [38;5;28;01mdef[39;00m [38;5;21mFileCodeBox[39m(file, lang, number[38;5;241m=[39m[38;5;28;01mFalse[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     66[0m     [38;5;66;03m#open text file in read mode[39;00m
[0;32m---> 67[0m     text_file [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     68[0m     [38;5;66;03m#read whole file to a string[39;00m
[1;32m     69[0m     data [38;5;241m=[39m text_file[38;5;241m.[39mread()

File [0;32m/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py:286[0m, in [0;36m_modified_open[0;34m(file, *args, **kwargs)[0m
[1;32m    279[0m [38;5;28;01mif[39;00m file [38;5;129;01min[39;00m {[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m2[39m}:
[1;32m    280[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    281[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIPython won[39m[38;5;124m'[39m[38;5;124mt let you open fd=[39m[38;5;132;01m{[39;00mfile[38;5;132;01m}[39;00m[38;5;124m by default [39m[38;5;124m"[39m
[1;32m    282[0m         [38;5;124m"[39m[38;5;124mas it is likely to crash IPython. If you know what you are doing, [39m[38;5;124m"[39m
[1;32m    283[0m         [38;5;124m"[39m[38;5;124myou can use builtins[39m[38;5;124m'[39m[38;5;124m open.[39m[38;5;124m"[39m
[1;32m    284[0m     )
[0;32m--> 286[0m [38;5;28;01mreturn[39;00m [43mio_open[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/jovyan/unixasm/empty.s'
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/unixasm/empty.s'

